#!/bin/bash
  
 cd
 rm -rf CCMINER-SERVER
 git clone https://github.com/saengx/CCMINER-GITHUB
 cd ../etc/mobile-mining/set-miner
 cp -r online.json offline.json /../root/CCMINER-GITHUB/mobile-mining/set-miner 
 cd
 cd ../etc
 rm -rf mobile-mining
 cd
 cd ../bin
 rm -rf add-ip edit-miner run-miner update backup restore
 cd
 cd CCMINER-GITHUB
 chmod +x setupdate.sh
 sh setupdate.sh
